import type { IMIItem } from "@/types/experiment";

export const IMI_ITEMS: IMIItem[] = [
  {
    id: "ie1",
    text: "I enjoyed doing this activity very much.",
    zh: "我非常喜歡做這個活動。",
    sub: "interest",
    rev: false,
  },
  {
    id: "ie2",
    text: "This activity was fun to do.",
    zh: "這個活動很有趣。",
    sub: "interest",
    rev: false,
  },
  {
    id: "ie3",
    text: "I thought this was a boring activity.",
    zh: "我覺得這個活動很沉悶。",
    sub: "interest",
    rev: true,
  },
  {
    id: "ie4",
    text: "This activity did not hold my attention at all.",
    zh: "這個活動完全沒有吸引我的注意力。",
    sub: "interest",
    rev: true,
  },
  {
    id: "ie5",
    text: "I would describe this activity as very interesting.",
    zh: "我會說這個活動非常有趣。",
    sub: "interest",
    rev: false,
  },
  {
    id: "pc1",
    text: "I think I am pretty good at this activity.",
    zh: "我覺得我在這個活動中表現得不錯。",
    sub: "competence",
    rev: false,
  },
  {
    id: "pc2",
    text: "I think I did pretty well at this activity.",
    zh: "我覺得我在這個活動中做得很好。",
    sub: "competence",
    rev: false,
  },
  {
    id: "pc3",
    text: "I am satisfied with my performance at this task.",
    zh: "我對自己在這個任務中的表現感到滿意。",
    sub: "competence",
    rev: false,
  },
  {
    id: "pc4",
    text: "I was pretty skilled at this activity.",
    zh: "我在這個活動中相當熟練。",
    sub: "competence",
    rev: false,
  },
  {
    id: "ef1",
    text: "I put a lot of effort into this.",
    zh: "我在這個活動中付出了很多努力。",
    sub: "effort",
    rev: false,
  },
  {
    id: "ef2",
    text: "I tried very hard on this activity.",
    zh: "我在這個活動中非常努力。",
    sub: "effort",
    rev: false,
  },
  {
    id: "ef3",
    text: "It was important to me to do well at this task.",
    zh: "對我來說，在這個任務中做好很重要。",
    sub: "effort",
    rev: false,
  },
  {
    id: "ef4",
    text: "I did not put much energy into this.",
    zh: "我沒有在這個活動中投入太多精力。",
    sub: "effort",
    rev: true,
  },
  {
    id: "pt1",
    text: "I did not feel nervous at all while doing this.",
    zh: "做這個活動時我一點也不緊張。",
    sub: "pressure",
    rev: true,
  },
  {
    id: "pt2",
    text: "I felt very tense while doing this activity.",
    zh: "做這個活動時我感到非常緊張。",
    sub: "pressure",
    rev: false,
  },
  {
    id: "pt3",
    text: "I was very relaxed in doing these.",
    zh: "做這些活動時我非常放鬆。",
    sub: "pressure",
    rev: true,
  },
  {
    id: "pt4",
    text: "I was anxious while working on this task.",
    zh: "做這個任務時我感到焦慮。",
    sub: "pressure",
    rev: false,
  },
  {
    id: "vu1",
    text: "I believe this activity could be of some value to me.",
    zh: "我認為這個活動對我有一定價值。",
    sub: "value",
    rev: false,
  },
  {
    id: "vu2",
    text: "I think this is a useful activity.",
    zh: "我覺得這是一個有用的活動。",
    sub: "value",
    rev: false,
  },
  {
    id: "vu3",
    text: "I think this is important for my learning.",
    zh: "我覺得這對我的學習很重要。",
    sub: "value",
    rev: false,
  },
  {
    id: "vu4",
    text: "I would be willing to do this again because it has value.",
    zh: "我願意再次做這個活動，因為它有價值。",
    sub: "value",
    rev: false,
  },
];
